### ISSUE TITLE
SSL Cert verification failing with new Docraptor client on Linux/Python client docraptor 0.2.1

### ISSUE THREAD

**Issue by zopyx** [DocRaptor/docraptor-python#4]
We are running Linux OpenSuse LEAP 42.1.

With the latest docraptor==0.2.1 client (Python) we receive the folloing error (likely because of some issue with the local cert store of OpenSuse. I suggest that the Python API should receive an optional parameter verify_cert=True|False (True by default) in order to have a workaround without hacking the Docraptor sources.

Andreas

```
https://docraptor.com//docs 
Traceback (most recent call last): 
 File "test.py", line 43, in <module> 
   "document_type": "pdf",                                         # pdf or xls or xlsx 
 File "/data/home/ajung/src/zopyx_ne.no/lib/python2.7/site-packages/docraptor/apis/doc_api.py", line 203, in create_doc 
   callback=params.get('callback')) 
 File "/data/home/ajung/src/zopyx_ne.no/lib/python2.7/site-packages/docraptor/api_client.py", line 325, in call_api 
   response_type, auth_settings, callback) 
 File "/data/home/ajung/src/zopyx_ne.no/lib/python2.7/site-packages/docraptor/api_client.py", line 149, in __call_api 
   post_params=post_params, body=body) 
 File "/data/home/ajung/src/zopyx_ne.no/lib/python2.7/site-packages/docraptor/api_client.py", line 361, in request 
   body=body) 
 File "/data/home/ajung/src/zopyx_ne.no/lib/python2.7/site-packages/docraptor/rest.py", line 204, in POST 
   body=body) 
 File "/data/home/ajung/src/zopyx_ne.no/lib/python2.7/site-packages/docraptor/rest.py", line 165, in request 
   raise ApiException(status=0, reason=msg) 
docraptor.rest.ApiException: (0) 
Reason: SSLError 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by jqr** [comment]
I'm looking at bundling some of these certs so clients aren't so dependent on OS certs, but in the mean You should be able to disable this using the [`verify_ssl` option](https://github.com/DocRaptor/docraptor-python/blob/d9ca2cb43b1488b8ce75e8f9901f4a483cde64d4/docraptor/configuration.py#L91-L93).

If you're using our example code from the README, the option would look like this:

```python
docraptor.configuration.username = "YOUR_API_KEY_HERE"
docraptor.configuration.verify_ssl = False
```

**Comment by jqr** [comment]
Please let me know if this work-around fixes it for you.

**Comment by jqr** [comment]
I think the suggested fix resolves the issue, but @zopyx feel free to re-open if it doesn't work.
